Repository kasuncfdo/hacktoberfest-2023, pull requests merged in 2023-10, with the labels that each got.

#1 Added updated version of admin login
  admin_login.php
Labels: hacktoberfest-accepted

#2 updated admin dashboard
  admin_dashboard.php
Labels: enhancement, hacktoberfest-accepted

#3 Added Create post.php
  create_post.php
Labels: hacktoberfest-accepted

#5 Update 404.html
  404.html
Labels: enhancement, hacktoberfest-accepted

#7 Added PHP Secure Vulnerability Report
  public/PHP Secure Vulnerability Report for x.pdf
Labels: hacktoberfest-accepted, issues
